### ISSUE TITLE
Upgrading from v0.9.7 to v3.13.0

### ISSUE THREAD

**Issue by bertvh** [joost-de-vries/sbt-tslint#2]
I just replaced this

```
addSbtPlugin("name.de-vries" % "sbt-tslint" % "0.9.7") // works
```

with 

```
addSbtPlugin("name.de-vries" % "sbt-tslint" % "3.13.0") // does not resolve
```

Sbt tries to get the following file, which does not exist

```
https://dl.bintray.com/sbt/sbt-plugin-releases/name/de-vries/sbt-tslint_2.10_0.13/3.13.0/sbt-tslint-3.13.0.pom
```

Any ideas what I'm doing wrong?

**Comment by joost-de-vries** [comment]
What version of sbt are you using?

When I throw away my local versions of sbt-tslint and I rebuild the activator template it resolves just fine. 

```
[info] Loading global plugins from /Users/joost1/.sbt/0.13/plugins/project
[info] Loading global plugins from /Users/joost1/.sbt/0.13/plugins
[info] Loading project definition from /Users/joost1/source/play-angular2-typescript-template/project/project
[info] Loading project definition from /Users/joost1/source/play-angular2-typescript-template/project
[info] Updating {file:/Users/joost1/source/play-angular2-typescript-template/project/}play-angular2-typescript-template-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/name.de-vries/sbt-tslint/scala_2.10/sbt_0.13/3.13.0/jars/sbt-tslint.jar ...
[info]  [SUCCESSFUL ] name.de-vries#sbt-tslint;3.13.0!sbt-tslint.jar (1780ms)
[info] Done updating.
```

I notice that your build tries to resolve a maven pom. One of the more recent sbt versions started support for a shared resolver for sbt plugins. sbt-tslint is using that resolver.
At the same time: the previous version used the same resolver. Hm.
Have you configured your resolvers in plugins.sbt in any special way?

Can you build the activator template correctly?

**Comment by bertvh** [comment]
Hi Joost,

Deleting my ivy cache did the trick. Pretty strange since the artifact shouldn't have been there (yet) in the first place.

I also have added these resolvers (not sure if that has anything to do with it) : `Resolver.sbtPluginRepo("release"),  Resolver.jcenterRepo`

Thanks.
